# Copyright © 2024 Nox Ignis.
# This file is part of Red Kangaroo OS Project.

[build]
target = "x86_64-unknown-linux-gnu"

[profile.release]
panic = "abort"
codegen-units = 1
opt-level = "z"
strip = "symbols"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-musl-gcc"
